from config import BASE_URL, TOKEN, MODEL
from meshapi import (
    ChatCompletionParams,
    ChatMessage,
    Tool,
    ToolFunction,
    MeshAPI,
    MeshAPIError,
)

client = MeshAPI(base_url=BASE_URL, token=TOKEN)

print(f"Using BASE_URL: {BASE_URL}")
print(f"Using MODEL: {MODEL}")

# 1. Ask a question that requires a tool
messages = [ChatMessage(role="user", content="What is the weather in Paris?")]
tools = [
    Tool(
        type="function",
        function=ToolFunction(
            name="get_weather",
            description="Get current weather for a city",
            parameters={
                "type": "object",
                "properties": {"city": {"type": "string"}},
                "required": ["city"],
            },
        ),
    )
]

try:
    print("\n--- Phase 1: Sending initial request ---")
    params = ChatCompletionParams(
        model=MODEL,
        messages=messages,
        tools=tools,
        tool_choice="auto",
    )

    resp = client.chat.completions.create(params)
    assistant_msg = resp.choices[0].message

    print(f"Assistant response role: {assistant_msg.role}")
    if assistant_msg.content:
        print(f"Assistant content: {assistant_msg.content}")

    if assistant_msg.tool_calls:
        print(f"Assistant requested {len(assistant_msg.tool_calls)} tool calls.")
        
        # Add assistant message (including tool calls) to history
        messages.append(ChatMessage(
            role="assistant",
            content=assistant_msg.content,
            tool_calls=assistant_msg.tool_calls
        ))
        
        # 2. Simulate tool execution and add results to messages
        for tool_call in assistant_msg.tool_calls:
            print(f"  Tool Call ID: {tool_call.id}")
            print(f"  Function: {tool_call.function.name}")
            print(f"  Arguments: {tool_call.function.arguments}")
            
            # Mock tool result
            tool_result = '{"temperature": 22, "unit": "celsius", "description": "Sunny"}'
            
            messages.append(ChatMessage(
                role="tool",
                tool_call_id=tool_call.id,
                content=tool_result
            ))
        
        # 3. Send the full conversation back to the model
        print("\n--- Phase 2: Sending tool results back ---")
        final_params = ChatCompletionParams(
            model=MODEL,
            messages=messages,
            tools=tools, # Still provide tools so it knows what they were
        )
        
        final_resp = client.chat.completions.create(final_params)
        final_msg = final_resp.choices[0].message
        
        print(f"Final Assistant response role: {final_msg.role}")
        print(f"Final response content: {final_msg.content}")
        print("\n[SUCCESS] Tool call round-trip completed.")

    else:
        print("\n[INFO] No tool calls were generated by the model.")
        if assistant_msg.content:
            print(f"Model just replied: {assistant_msg.content}")

except MeshAPIError as e:
    print(f"\n[ERROR] MeshAPI error: {e}")
except Exception as e:
    print(f"\n[ERROR] Unexpected error: {e}")
    import traceback
    traceback.print_exc()
finally:
    client.close()
